=== Kovalevskyi-Academy/itg/Open_API/node.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "node.json",
  "title": "NODE",
  "description": "This is the smallest unit of the whole history.",
  "type": "object",
  "required": [
    "storyUuid",
    "nodeTitle",
    "content"
  ],
  "properties": {
    "nodeUuid": {
      "description": "Unique identifier of each node.",
      "existingJavaType": "java.util.UUID",
      "readOnly": true,
      "updatable": false,
      "example": "7131532b-6053-4380-bc7d-179ee146a111"
    },
    "storyUuid": {
      "description": "The unique ID of the story to which the node belongs.",
      "existingJavaType": "java.util.UUID",
      "readOnly": true,
      "updatable": false,
      "example": "7131532b-6053-4380-bc7d-179ee146aa6c"
    },
    "nodeTitle": {
      "description": "The name the author gave to the node.",
      "type": "string",
      "pattern": "^(.*)$",
      "minLength": 1,
      "maxLength": 150,
      "example": "Dao begins with the first step."
    },
    "content": {
      "description": "For now, only not formatted text.",
      "type": "string",
      "minLength": 1,
      "maxLength": 1500,
      "example": "In the beginning there was light.\nThe baby elephant woke up from a bright light in his eyes. The midday sun was already high above the horizon. Not understanding what was happening, he somehow got to his feet and looked around: there was a hemp field all around."
    },
    "choices": {
      "description": "The Map of possible choices for that particular node. From zero or more.",
      "existingJavaType": "java.util.Map<java.lang.String, java.util.UUID>",
      "minItems": 0,
      "uniqueItems": true,
      "example": [
        {
          "essenceOfChoice": "Indulge in hemp oblivion.",
          "nextNodeUuid": "7131532b-6053-4380-bc7d-179ee146a222"
        },
        {
          "essenceOfChoice": "It's time to get out of this hemp hell!",
          "nextNodeUuid": "7131532b-6053-4380-bc7d-179ee146a333"
        }
      ]
    }
  }
}

=== Kovalevskyi-Academy/itg/scripts/testObjects/node1.json
{
  "nodeUuid": null,
  "storyUuid": "fa2c2a87-e04c-4c7e-8bcc-a4c86514e5b0",
  "nodeTitle": "First node",
  "content": "It is node's content of first node.",
  "choices": {
    "First choice for first node": "e5205d6c-d3a9-4957-812a-bb6bcee3f916",
    "Second choice for first node": "8c3c8b7e-d082-43ed-ba56-1dac2039f1e5"
  }
}
